<?php

namespace Banko\Bundle\CompteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * MouvementAutomatiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouvementAutomatiqueRepository extends EntityRepository
{
   /**
    * Retourne les mouvements automatiques d'un compte
    *
    * @return array
    * @access public
    */
    public function getMouvementAutomatiqueActifCompte($compte_id) 
    {
    	$qb = $this->_em->createQueryBuilder()
                ->select("ma")
    		->from("BankoCompteBundle:MouvementAutomatique", "ma")
    		->where("ma.compte = '".$compte_id."'")
                ->andWhere("ma.actif = 1");

        return $qb->getQuery()->getResult(Query::HYDRATE_ARRAY);
    }  
}
