<?php

namespace Banko\Bundle\CompteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MouvementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouvementRepository extends EntityRepository
{
}
