<?php

namespace Banko\Bundle\CompteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * mouvementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mouvementRepository extends EntityRepository
{
}
